// Generated by CoffeeScript 1.9.2
(function() {
  (function($) {

    /*
    	 * The hash
    	theHash = window.location.hash.substr(1)
    
    	 * Split hash
    	splittedHash = theHash.split("&")
    
    	 * Obtain the token from url
    	accessToken = false
    	$.each splittedHash, (index, val) -> 
    		if val.indexOf("access_token") > -1
    			 * The token
    			accessToken = val.split("access_token=")[1]
    
    	 * Check if we have accesstoken
    	if accessToken is false
    		 * Redirect
    		utubeClientId = "923680594690-39qgo36bob9vd0roo5jpkj4pfdikcmcm.apps.googleusercontent.com"
    		utubeRedirectUri = "http://localhost/github/ApiApp/"
    		utubeScope = "https://www.googleapis.com/auth/youtube"
    		window.location.href = "https://accounts.google.com/o/oauth2/auth?client_id=#{utubeClientId}&redirect_uri=#{utubeRedirectUri}&scope=#{utubeScope}&response_type=token&pageId=none"
    
    	else
    		 * We have token! :D
     */
    var search;
    $(document).ready(function() {
      var searchFixedWidth;
      searchFixedWidth = 690;
      $("[data-search]").css("width", searchFixedWidth);
      return $(document).on("keyup input", "[data-search]", function(e) {
        var $inputSize, $span;
        $(this).closest(".search").removeClass("has-searched");
        if ($(this).val().length === 0) {
          return $(this).stop().animate({
            width: searchFixedWidth
          }, {
            duration: 200
          });
        } else {
          $span = $(this).siblings("span").first();
          $span.text($(this).val());
          $span.css("display", "inline-block");
          $inputSize = $span.outerWidth();
          $span.css("display", "");
          $(this).stop();
          return $(this).css("width", $inputSize);
        }
      });
    });
    $(document).on("keydown", "[data-search]", function(event) {
      var val;
      if (event.which === 13) {
        val = $(this).val();
        return search(val, function() {
          return $("[data-search]").closest(".search").addClass("has-searched");
        });
      }
    });
    return search = function(query, callback) {
      var apiKey, settings, useVideos;
      settings = "type=video&maxResults=5";
      apiKey = "AIzaSyBcN17dQgPoR3pAfZsFDiorljShq2lcpXI";
      $.ajax({
        url: "https://www.googleapis.com/youtube/v3/search?part=snippet&q=" + query + "&" + settings + "&key=" + apiKey,
        dataType: "jsonp",
        success: function(data) {
          var items, videoList;
          items = data.items;
          videoList = [];
          return $.each(items, function(index, val) {
            return $.ajax({
              url: "https://www.googleapis.com/youtube/v3/videos?id=" + val.id.videoId + "&part=snippet,statistics&key=" + apiKey,
              dataType: "jsonp",
              success: function(data) {
                videoList.push(data.items[0]);
                if (videoList.length === items.length) {
                  useVideos(videoList);
                  return callback();
                }
              }
            });
          });
        }
      });
      return useVideos = function(videos) {
        var $container;
        console.log(videos);
        $container = $(".items");
        $container.html("");
        return $.each(videos, function(index, item) {
          var $image, $info, $item, $video, dislikes, likes;
          $item = $("<div/>");
          $video = $("<iframe/>", {
            width: 640,
            height: 360,
            src: "https://www.youtube.com/embed/" + item.id,
            frameborder: 0,
            allowfullscreen: true,
            css: {
              display: "none"
            }
          });
          $image = $("<div/>", {
            css: {
              backgroundImage: "url(" + item.snippet.thumbnails.standard.url + ")",
              backgroundSize: "cover",
              backgroundPosition: "center",
              width: 640,
              height: 360,
              cursor: "pointer"
            }
          });
          $image.click(function() {
            $(this).remove();
            return $video.css("display", "");
          });
          likes = item.statistics.likeCount.replace(/\B(?=(\d{3})+(?!\d))/g, " ");
          dislikes = item.statistics.dislikeCount.replace(/\B(?=(\d{3})+(?!\d))/g, " ");
          $info = $("<div/>");
          $info.append("<strong>" + item.snippet.title + "</strong>");
          $info.append("<p>Likes: " + likes + "</p>");
          $info.append("<p>Dislikes: " + dislikes + "</p>");
          $item.append($image);
          $item.append($video);
          $item.append($info);
          return $container.append($item);
        });
      };
    };
  })(jQuery);

}).call(this);
